### ISSUE TITLE
I have a question ...

### ISSUE THREAD

**Issue by DaHoopster** [lemariva/uPyM5BLE#1]
Wondering if using a combination of the official MicroPython with uPyM5BLE would allow me to use all the original APIs from the M5Stack version. If it does, 🙌 ; if it doesn't, is there a way 🤔 ? Thanks!

**Comment by lemariva** [comment]
There are may be two ways to do that:

1. You can fork the m5stack/M5Stack_MicroPython, which is a fork from loboris/MicroPython_ESP32_psRAM_LoBo and update the MicroPython version.
2. You can freeze the m5stack modules (follow steps in [this article](https://lemariva.com/blog/2020/03/tutorial-getting-started-micropython-v20) - section "Freeze modules on MicroPython") and check if that works. The m5stack modules are localted [here](https://github.com/m5stack/M5Stack_MicroPython/tree/master/MicroPython_BUILD/components/micropython/esp32/modules). I didn't test it, but it should work if there are no other dependencies/modules written in C.

Keep me updated! Thanks

**Comment by DaHoopster** [comment]
Thanks for your reply @lemariva. I am trying to enable Bluetooth on the M5Stack Fire.

I am not familiar with how to update the MicroPython version for M5Stack. I *think* I need to first build the MicroPython firmware by following [this](https://github.com/micropython/micropython/tree/master/ports/esp32), but I am not sure what happens next. Could you help me?

**Comment by lemariva** [comment]
Follow the steps of this tutorial: https://lemariva.com/blog/2020/03/tutorial-getting-started-micropython-v20
